{% set name = "kfac-jax" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 5f0436691bf7673c49e975f6b2cb5156e23199823b55e71c276af4daa19d08a2

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - typing_extensions >=4.0.0
    - python >={{ python_min }}
    - absl-py >=0.12.0
    - immutabledict >=2.2.1
    - numpy >=1.22
    - distrax >=0.1.3
    - jax >=0.4.27
    - jaxlib >=0.4.27
    - dm-tree >=0.1.7
    - optax >=0.1.4
    - typing-extensions >=4.2.0
    - tensorflow-estimator

test:
  imports:
    - kfac_jax
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/deepmind/kfac-jax
  summary: A Jax package for approximate curvature estimation and optimization using KFAC.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
