{% set name = "kfac-jax" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kfac-jax-{{ version }}.tar.gz
  sha256: 32b065fe204f6cdd62a2f17b68f32cc863ba1a834034235654893771a7815c7e

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - absl-py >=0.12.0
    - immutabledict >=2.2.1
    - numpy >=1.21
    - distrax >=0.1.3
    - jax >=0.4.7
    - jaxlib >=0.4.7
    - dm-tree >=0.1.7
    - optax >=0.1.4
    - typing-extensions >=4.2.0
    - tensorflow-estimator

test:
  imports:
    - kfac_jax
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/deepmind/kfac-jax
  summary: A Jax package for approximate curvature estimation and optimization using KFAC.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
